version: '3.8'

services:
  enrich:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: enrich
      POSTGRES_PASSWORD: enrich
      POSTGRES_DB: enrich
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local